esphome:
  name: "kobs"
  friendly_name: "kobs"

esp8266:
  board: esp01_1m
mqtt:
  broker: !secret mqtt
  username: koushik
  password: Applez35

  topic_prefix: kobs
  birth_message:
    topic: kobs/status
    payload: online
  will_message:
    topic: kobs/status
    payload: offline

# Enable logging
logger:
  level: ERROR
# Enable Home Assistant API
#api:
#  encryption:
#    key: "+/PAgnM+UzL9Qh8PvEkGtZGke40eFj1CY0aBUwkHAZQ="

ota:
  password: "a3b5587fa927b11aa52deaa762791f26"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 10.0.1.1
    gateway: 10.0.0.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "kbs Fallback Hotspot"
    password: "QqkgWX0bq4R5"

captive_portal:

button:
    - platform: wake_on_lan
      name: "Turn on Tv"
      target_mac_address: 08:28:02:A3:BF:C1
sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s    
switch:
  - platform: gpio
    pin:
      number: 5
      inverted: true
    name: "Profile Light"
    id: pf
    icon: "mdi:toggle-switch"  
  - platform: gpio
    pin:
      number: 2
      inverted: true
    name: "Strip Light"
    id: sl
    icon: "mdi:toggle-switch"
  - platform: gpio
    pin:
      number: 4
      inverted: true
    name: "Spot Light"
    id: sp
    icon: "mdi:toggle-switch"
  - platform: gpio
    pin:
      number: 0
      inverted: true
    name: "Under Bed Light"
    id: ub
    icon: "mdi:toggle-switch"
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "profile-light switch"
    on_press:
      then:
       - switch.turn_on: pf
    on_release:
      then:
        - switch.turn_off: pf

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Strip-light Switch"
    on_press:
      then:
       - switch.turn_on: sl
       - switch.turn_on: ub
    on_release:
      then:
        - switch.turn_off: sl
        - switch.turn_off: ub
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    name: "Spot-light Switch"
    on_press:
      then:
       - switch.turn_on: sp  
    on_release:
      then:
        - switch.turn_off: sp
  